[package]
name = "rust-chat-app"
version = "0.1.0"
edition = "2021"



[dependencies]
warp = "0.3.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3.21"
tokio-stream = "0.1.7"
log = "0.4.14"
env_logger = "0.8.4"
jsonwebtoken = "7.2.0"
